travis:
  secure:
    BINSTAR_TOKEN: rTU5DDqtHJAyu0oalbYQQRt6TCQ8OEIMzX6JYmiUqikGr7ANB0O2tXaOF0ywAkFwuYgnHHhVsDbCBBQaQMYeo1txCN+FQ2chWyaYDol2VzC4Y1ZFkaMvlHD+f5R9ckGqH4zg8oSK5Fy4c+dmmnN8tcBOF0XurUkIwkb6rp9R8OkOtE7RoEZ9F7NFGxgFnNU2GQvuE7v8GTD6enciGc/C6Y/GZ50lewRyM7R6pSUrG/NsNod7GR8koimlsWpDx3/OApuyiCjPODW5p9/6lf8x0cuVLmplPxMvkgp1WBDEi6Rg9FDLjhX/WjLmB17xHhG0EQvtvhaeE/SGiWxctZENQLvnVzZtdmls19XZbWnw2vOcF36GI7KRy4DeLiO439UZepQoLXUObcQDRSsYvRYOG3AAduTRYftVh7dkO98eR2Ecml0TwiNe5lm3ST5AjV15CGxtpqOVcbmlhWSK+cOmbsZAEv0QuYiFsL6ku5XwHhrHfbBo3SLOhJ3sDEM8+i2ubukfDFXWlADQGPeP7/jh/xMmTRuQoSQlpWTOZvZdPA48G197RNWBbkDMVRCvBFBQkXJHJZavTcU4OJ7TyjqGucIQXFt/u0y2M72K266tKNIfuADkVYO7LSv9if1o99LQ7xDf/4RLi2Et1LCc4gv89TfOJ97WWWSIBudw09Zu7QQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
